CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "persons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "cpf" varchar UNIQUE,
  "birth_date" date,
  "phone" varchar,
  "address" varchar NOT NULL,
  "neighborhood" varchar NOT NULL,
  "city" varchar NOT NULL,
  "zip_code" varchar,
  "status" varchar DEFAULT 'em_casa',
  "needs_vital_equipment" boolean DEFAULT false,
  "vital_equipment_description" text,
  "consent" boolean NOT NULL,
  "registered_by" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "medications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" integer,
  "name" varchar NOT NULL,
  "dosage" varchar,
  "frequency" varchar,
  "notes" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "material_needs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" integer,
  "category" varchar,
  "description" text,
  "fulfilled" boolean DEFAULT false,
  "fulfilled_at" timestamp,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "persons"."consent" IS 'Obrigatório por LGPD';

ALTER TABLE "persons" ADD FOREIGN KEY ("registered_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "medications" ADD FOREIGN KEY ("person_id") REFERENCES "persons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "material_needs" ADD FOREIGN KEY ("person_id") REFERENCES "persons" ("id") DEFERRABLE INITIALLY IMMEDIATE;
